name: Build CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Cache JDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.sdkman
            ~/.java
            ~/.m2/toolchains.xml
          key: jdk-${{ runner.os }}-17-temurin

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test report with jacoco
        run: ./gradlew jacocoTestReport --stacktrace

      - name: Build with Gradle
        run: ./gradlew assembleDevelopDebug --stacktrace